server:
  port: 80
eureka:
  client:
    service-url:
      # 指定eureka server 地址
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
  instance:
    instance-id: cloud-order-openfeign-consumer80
spring:
  application:
    name: cloud-order-consumer

logging:
  level:
    com.itbaizhan.service: debug
