server:
  port: 7002
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
  client:
    # 表示是否将自己注册到eureka服务上
    register-with-eureka: false
    # 表示是否从eureka server 获取注册的服务信息
    fetch-registry: false
    # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://localhost:7001/eureka/
