server:
  port: 8001
eureka:
  instance:
    # 实例名字
    instance-id: cloud-payment-provider8001
  client:
    service-url:
      # Eureka 服务地址
      # defaultZone: http://localhost:7001/eureka/
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
spring:
  application:
    # 设置应用名字
    name: cloud-payment-provider
